Models/MeetingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MeetingApp.Models
{
    public class MeetingInfo
    {
        public int Id { get; set; }
        public string? Location { get; set; }
        public DateTime Date { get; set; }
        public int NumberOfPeople { get; set; }
    }
}

Models/Repository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MeetingApp.Models
{
    public class Repository
    {
        private static List<UserInfo> _users = new();

        static Repository()
        {
            _users.Add(new UserInfo() { Id = 1, Name = "Ali", Email = "abc@gmail.com", Phone = "123", WillAttend = true });
            _users.Add(new UserInfo() { Id = 2, Name = "Veli", Email = "abcd@gmail.com", Phone = "1234", WillAttend = false });
            _users.Add(new UserInfo() { Id = 3, Name = "Demir", Email = "abde@gmail.com", Phone = "12345", WillAttend = true });
        }

        public static List<UserInfo> Users
        {
            get
            {
                return _users;
            }
        }

        public static void CreateUser(UserInfo user)
        {
            user.Id = Users.Count + 1;
            _users.Add(user);
        }

        public static UserInfo? GetById(int id)
        {
            return _users.FirstOrDefault(user => user.Id == id);
        }
    }
}

Models/UserInfo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MeetingApp.Models
{
    public class UserInfo
    {

        public int Id { get; set; }

        [Required(ErrorMessage = "Ad alanı zorunlu")]
        public string? Name { get; set; }

        [Required(ErrorMessage = "Telefon alanı zorunlu")]
        public string? Phone { get; set; }

        [Required(ErrorMessage = "Email alanı zorunlu")]
        [EmailAddress]
        public string? Email { get; set; }

        [Required]
        public bool WillAttend { get; set; }
    }
}

Controllers/HomeController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            int hour = DateTime.Now.Hour;

            ViewData["Greeting"] = hour > 12 ? "İyi günler" : "Günaydın";
            // ViewData["UserName"] = "Emir";

            var meetingInfo = new MeetingInfo()
            {
                Id = 1,
                Location = "Bursa",
                Date = new DateTime(2024, 01, 20, 20, 0, 0),
                NumberOfPeople = 100
            };

            return View(meetingInfo);
        }
    }
}

Controllers/MeetingController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class MeetingController : Controller
    {
        [HttpGet]
        public IActionResult Apply()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Apply(UserInfo model)
        {
            if (ModelState.IsValid)
            {
                Repository.CreateUser(model);
                ViewBag.UserCount = Repository.Users.Where(info => info.WillAttend == true).Count();
                return View("Thanks", model);
            }
            else
            {
                return View(model);
            }
        }

        public IActionResult List()
        {
            return View(Repository.Users);
        }

        //meeting/details/id
        public IActionResult Details(int id)
        {
            return View(Repository.GetById(id));
        }
    }
}

Views/Home/Index.cshtml
@model MeetingInfo
@{
    ViewBag.Title = "Başvuru";
    Layout = "_Layout2";
}
<h1>@ViewData["Greeting"]</h1>
<p>Toplantı Katılım Durumunuzu Bildiriniz</p>
<div class="card my-2">
    <ul class="list-group list-group-flush">
        <li class="list-group-item">@Model.Location</li>
        <li class="list-group-item">@Model.Date.ToString("dd/MM/yyyy HH:mm:ss") Tarihinde Gerçekleşicek</li>
        <li class="list-group-item">@Model.NumberOfPeople Katılımcı</li>
    </ul>
</div>
<a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply">Başvuru Yap</a>

Views/Meeting/Apply.cshtml
@model UserInfo
@{
    ViewBag.Title = "Katılım Formu";
}
<h1 class="h4">Toplantı katılım formu</h1>
<form method="post" asp-controller="Meeting" asp-action="Apply" novalidate>
    <div asp-validation-summary="All"></div>
    <div class="mb-3 text-start">
        <label asp-for="Name" class="form-label">Adınız</label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="mb-3 text-start">
        <label asp-for="Email" class="form-label">E-posta Adresiniz</label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3 text-start">
        <label asp-for="Phone" class="form-label">Telefon Numaranız</label>
        <input asp-for="Phone" class="form-control">
    </div>
    <div class="mb-3 text-start">
        <label asp-for="WillAttend" class="form-label">Katılım Durumu</label>
        <select asp-for="WillAttend" class="form-select">
            <option value="">Seçiniz</option>
            <option value="true">Katılıyorum</option>
            <option value="false">Katılmıyorum</option>
        </select>
    </div>
    <div class="d-flex justify-content-start">
        <button class="btn btn-primary" type="submit">Başvuru Yap</button>
    </div>
</form>

Views/Meeting/Details.cshtml
@model UserInfo
@{
    ViewBag.Title = "Başvuru Detayı";
}
@{
    var className = @Model.WillAttend == true ? "primary" : "danger";
}
<main class="text-center">
    <h1 class="h4">Başvuru Detayı</h1>
    <p>
        <span class="badge text-bg-@className">
            @if (Model.WillAttend)
            {
                <span>Katılıyor</span>
            }
            else
            {
                <span>Katılmıyor</span>
            }
        </span>
    </p>
    <p>İsim : @Model.Name</p>
    <p>Email : @Model.Email</p>
    <p>Telefon : @Model.Phone</p>
    <p asp-controller="Meeting" asp-action="List" class="btn btn-outline-@className">Katılımcı Listesi</p>
</main>

Views/Meeting/List.cshtml
@model List<UserInfo>
@{
    ViewBag.Title = "Katılım Listesi";
}
<h1 class="h4">Toplantı Katılım listesi</h1>
<table class="table table-border">
    <thead>
        <tr>
            <td>Ad</td>
            <td>Katılım Durumu</td>
            <td>Detay</td>
        </tr>
    </thead>
    <tbody>
        @{
            int attemptedUsers = 0;
        }
        @foreach (var user in Model)
        {
            if (@user.WillAttend)
            {
                attemptedUsers++;
            }
            var durum = user.WillAttend == true ? "Evet" : "Hayır";
            var className = user.WillAttend == true ? "table-success" : "table-danger";
            <tr class="@className">
                <td>@user.Name</td>
                <td>@durum</td>
                <td>
                    <a class="btn btn-sm btn-primary" href="/meeting/details/@user.Id">Detay</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="card">
    <p class="text-center mt-3">@attemptedUsers kişi toplantıya katıldı</p>
</div>

Views/Meeting/Thanks.cshtml
@model UserInfo
@{
    ViewBag.Title = "Başvuru Durumu";
}
<main class="text-center">
    <h1 class="h4">Başvuru Durumu</h1>
    @if (Model.WillAttend)
    {
        <p>Teşekkürler @Model.Name, toplantıya sizinle birlikte @ViewBag.UserCount kişi katılıyor.</p>
        <a class="btn btn-outline-primary" href="#">Katılımcıları listele</a>
    }
    else
    {
        <p>@Model.Name, toplantıya katılmadığından dolayı üzgünüz.</p>
        <a class="btn btn-outline-primary" href="/meeting/list">Katılımcıları listele</a>

    }
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
    <title>@ViewBag.Title - MeetingApp</title>
</head>

<body>
    <div class="bg-primary text-white p-2 text-center">Meeting App</div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto text-center">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
    <title>@ViewBag.Title - MeetingApp</title>
</head>
<body>
    <div class="bg-danger text-white p-2 text-center">Meeting App</div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto text-center">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>